"""DataCo Smart Supply Chain import and generated supporting business data.

The Kaggle CSV is the primary dataset.  It has products, orders and delivery
facts but no real supplier contracts/invoices/quality inspections, so those
supporting records are generated by the explicit demo seed, not downloaded.
"""
import csv
import io
import os
import uuid
from datetime import datetime, timedelta
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from pathlib import Path

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from sqlalchemy.orm import Session

from app.api.deps import get_current_user, require_roles
from app.core.database import get_db
from app.models.contract import Contract, ContractStatus
from app.models.communication import Message, MessageType
from app.models.document import DocumentType, VendorDocument
from app.models.operations import Delivery, DeliveryStatus, Invoice, InvoiceStatus, Product, PurchaseOrderItem, QualityInspection
from app.models.performance import PerformanceRecord
from app.models.purchase_order import POStatus, PurchaseOrder
from app.models.user import RoleEnum, User
from app.models.vendor import Vendor, VendorCategory, VendorStatus
from app.services.activity import log_activity
from app.services.reliability import recompute_reliability_score


router = APIRouter(prefix="/imports", tags=["Data Management"])
IMPORT_ROLES = (RoleEnum.ADMIN, RoleEnum.PROCUREMENT_MANAGER)


def _number(value, default=0) -> Decimal:
    try:
        return Decimal(str(value or default).replace(",", "").replace("$", "")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    except (InvalidOperation, ValueError):
        return Decimal(str(default))


def _integer(value, default=0) -> int:
    try:
        return int(float(str(value or default)))
    except (TypeError, ValueError):
        return default


def _date(value) -> datetime | None:
    if not value:
        return None
    text = str(value).strip()
    for fmt in ("%m/%d/%Y %H:%M", "%m/%d/%Y %H:%M:%S", "%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            pass
    return None


def _category_for_dataco(value: str | None) -> VendorCategory:
    name = (value or "General").lower()
    if any(word in name for word in ("tech", "computer", "electronic", "smart")):
        return VendorCategory.IT
    if any(word in name for word in ("shipping", "logistic", "transport", "delivery")):
        return VendorCategory.LOGISTICS
    if any(word in name for word in ("tool", "equipment", "fitness", "machine")):
        return VendorCategory.EQUIPMENT
    if any(word in name for word in ("maint", "repair")):
        return VendorCategory.MAINTENANCE
    if any(word in name for word in ("service", "book", "video")):
        return VendorCategory.SERVICE_PROVIDER
    return VendorCategory.RAW_MATERIAL


def _row(row: dict[str, str], *names: str) -> str:
    normalized = {str(key).strip().lower(): value for key, value in row.items() if key}
    for name in names:
        value = normalized.get(name.lower())
        if value not in (None, ""):
            return str(value).strip()
    return ""


def _dataco_vendor(db: Session, category_name: str) -> Vendor:
    company_name = f"DataCo {category_name or 'General'} Supply Partners"
    vendor = db.query(Vendor).filter(Vendor.company_name == company_name).first()
    if vendor:
        return vendor
    vendor = Vendor(
        company_name=company_name,
        category=_category_for_dataco(category_name),
        status=VendorStatus.APPROVED,
        contact_name="DataCo Supply Desk",
        contact_email="supplydesk@dataco.demo",
        country="United States",
        registration_date=datetime.utcnow(),
    )
    db.add(vendor)
    db.flush()
    return vendor


@router.post("/dataco", dependencies=[Depends(require_roles(*IMPORT_ROLES))])
async def import_dataco_csv(
    file: UploadFile = File(...),
    max_rows: int = Form(1000, ge=1, le=5000),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Imports DataCoSupplyChainDataset.csv in manageable batches.

    Dataset columns are read by their official headings and are intentionally
    tolerant of case/spacing variations in exported CSVs.
    """
    if not file.filename or not file.filename.lower().endswith(".csv"):
        raise HTTPException(status_code=422, detail="Upload the DataCo CSV file (.csv)")
    content = await file.read()
    if len(content) > 30 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="CSV is too large for one local import. Use 5,000-row exports.")
    try:
        text = content.decode("utf-8-sig")
    except UnicodeDecodeError:
        text = content.decode("latin-1")
    reader = csv.DictReader(io.StringIO(text))
    if not reader.fieldnames or not any(str(header).strip().lower() == "product name" for header in reader.fieldnames):
        raise HTTPException(status_code=422, detail="This does not look like the DataCo Smart Supply Chain CSV: Product Name column is required.")

    counts = {"rows_read": 0, "vendors_created": 0, "products_created": 0, "purchase_orders_created": 0, "delivery_records_created": 0}
    seen_vendor_names = {name for (name,) in db.query(Vendor.company_name).all()}
    performance = {}
    for row in reader:
        if counts["rows_read"] >= max_rows:
            break
        product_name = _row(row, "Product Name")
        order_id = _row(row, "Order Id", "Order ID")
        if not product_name or not order_id:
            continue
        counts["rows_read"] += 1
        category_name = _row(row, "Category Name") or "General"
        company_name = f"DataCo {category_name} Supply Partners"
        vendor = _dataco_vendor(db, category_name)
        if company_name not in seen_vendor_names:
            counts["vendors_created"] += 1
            seen_vendor_names.add(company_name)

        product_ref = _row(row, "Product Card Id", "Order Item Cardprod Id") or product_name
        sku = f"DCO-{product_ref}"[:80]
        price = _number(_row(row, "Order Item Product Price", "Product Price", "Sales"))
        product = db.query(Product).filter(Product.sku == sku).first()
        if not product:
            product = Product(
                vendor_id=vendor.id, sku=sku, product_name=product_name[:200], category=category_name[:120],
                unit_price=price, stock_unit=_integer(_row(row, "Order Item Quantity"), 0),
                lead_time_days=_integer(_row(row, "Days for shipment (scheduled)"), 0), source_reference=product_ref[:100],
            )
            db.add(product)
            db.flush()
            counts["products_created"] += 1

        po_number = f"DCO-{order_id}"[:30]
        quantity = max(1, _integer(_row(row, "Order Item Quantity"), 1))
        line_total = _number(_row(row, "Order Item Total", "Sales"), price * quantity)
        order_date = _date(_row(row, "order date (DateOrders)", "Order Date")) or datetime.utcnow()
        scheduled_days = _integer(_row(row, "Days for shipment (scheduled)"), 0)
        expected_date = order_date + timedelta(days=scheduled_days) if scheduled_days else None
        shipping_date = _date(_row(row, "shipping date (DateOrders)", "Shipping Date"))
        delivery_text = _row(row, "Delivery Status", "Order Status").lower()
        po = db.query(PurchaseOrder).filter(PurchaseOrder.po_number == po_number).first()
        new_po = not po
        if new_po:
            po = PurchaseOrder(
                po_number=po_number, vendor_id=vendor.id, requested_by_id=current_user.id,
                description=f"Imported DataCo order: {product_name}"[:1000], quantity=quantity, unit_price=price,
                total_amount=line_total, expected_delivery_date=expected_date,
                actual_delivery_date=shipping_date, status=POStatus.DELIVERED if shipping_date else POStatus.ORDERED,
            )
            db.add(po)
            db.flush()
            counts["purchase_orders_created"] += 1
        item_ref = _row(row, "Order Item Id") or product_ref
        item_name = f"DCO-{order_id}-{item_ref}"[:80]
        item_exists = db.query(PurchaseOrderItem.id).filter(PurchaseOrderItem.item_name == item_name, PurchaseOrderItem.purchase_order_id == po.id).first()
        if not item_exists:
            if not new_po:
                po.total_amount = (Decimal(str(po.total_amount)) + line_total).quantize(Decimal("0.01"))
            db.add(PurchaseOrderItem(purchase_order_id=po.id, product_id=product.id, item_name=item_name, quantity=quantity, unit_price=price, total_amount=line_total))

        delivery_number = f"DCO-DLV-{order_id}-{item_ref}"[:50]
        if not db.query(Delivery.id).filter(Delivery.delivery_number == delivery_number).first():
            late = _integer(_row(row, "Late_delivery_risk"), 0) == 1 or "late" in delivery_text
            delay_days = max(0, (shipping_date.date() - expected_date.date()).days) if shipping_date and expected_date else (1 if late else 0)
            delivery_status = DeliveryStatus.DELIVERED if shipping_date else (DeliveryStatus.DELAYED if late else DeliveryStatus.IN_PROGRESS)
            db.add(Delivery(
                delivery_number=delivery_number, purchase_order_id=po.id, vendor_id=vendor.id,
                expected_delivery_date=expected_date, actual_delivery_date=shipping_date, status=delivery_status,
                delay_days=delay_days, received_goods=bool(shipping_date), delivery_notes=f"Imported DataCo delivery status: {delivery_text or 'unknown'}",
            ))
            counts["delivery_records_created"] += 1
            stats = performance.setdefault(vendor.id, {"on_time": 0, "delayed": 0})
            stats["delayed" if late else "on_time"] += 1

    for vendor_id, stats in performance.items():
        db.add(PerformanceRecord(
            vendor_id=vendor_id, recorded_by_id=current_user.id, on_time_deliveries=stats["on_time"],
            delayed_deliveries=stats["delayed"], quality_rating=4.2, response_time_hours=10,
            issue_resolution_hours=24, order_completion_rate=96,
        ))
    log_activity(db, current_user.id, "imported", "dataco_csv", None, f"{counts['rows_read']} DataCo rows from {file.filename}")
    db.commit()
    for vendor_id in performance:
        recompute_reliability_score(db, vendor_id)
    return {**counts, "message": "DataCo Smart Supply Chain data imported. Reliability and risk values were calculated by VendorIQ."}


@router.post("/demo-data", dependencies=[Depends(require_roles(RoleEnum.ADMIN))])
def load_generated_supporting_data(db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    """Creates realistic supporting data for fields not supplied by DataCo.

    This is deliberately idempotent and keeps existing user records untouched.
    """
    templates = [
        ("Global Steel Corp", VendorCategory.RAW_MATERIAL, "Steel Rods", "STEEL-100", Decimal("125.00"), 94, 0, 91),
        ("TechSupply Ltd", VendorCategory.IT, "Network Switch", "TECH-210", Decimal("890.00"), 46, 2, 88),
        ("QuickLogistics", VendorCategory.LOGISTICS, "Freight Service", "LOG-330", Decimal("420.00"), 33, 4, 78),
        ("BuildRight Services", VendorCategory.SERVICE_PROVIDER, "Site Safety Service", "BLD-410", Decimal("685.00"), 28, 5, 74),
        ("OneFix Maintenance", VendorCategory.MAINTENANCE, "Generator Maintenance", "MNT-520", Decimal("310.00"), 41, 1, 85),
        ("Apex Equipment", VendorCategory.EQUIPMENT, "Safety Helmet", "EQP-610", Decimal("38.00"), 37, 3, 81),
    ]
    created = {"vendors": 0, "products": 0, "purchase_orders": 0, "deliveries": 0, "invoices": 0, "quality_inspections": 0, "contracts": 0, "documents": 0, "messages": 0}
    vendor_ids = []
    for index, (company, category, product_name, sku, price, on_time, late, quality) in enumerate(templates, start=1):
        vendor = db.query(Vendor).filter(Vendor.company_name == company).first()
        if not vendor:
            vendor = Vendor(company_name=company, category=category, status=VendorStatus.APPROVED, contact_name="Operations Team", contact_email=f"contact{index}@vendoriq.demo", country="India", registration_date=datetime.utcnow())
            db.add(vendor)
            db.flush()
            created["vendors"] += 1
        vendor_ids.append(vendor.id)
        product = db.query(Product).filter(Product.sku == sku).first()
        if not product:
            product = Product(vendor_id=vendor.id, sku=sku, product_name=product_name, category=category.value, unit_price=price, stock_unit=250, lead_time_days=7 + index)
            db.add(product)
            db.flush()
            created["products"] += 1
        po_number = f"PO-DEMO-{1000 + index}"
        po = db.query(PurchaseOrder).filter(PurchaseOrder.po_number == po_number).first()
        if not po:
            expected = datetime.utcnow() - timedelta(days=20 - index)
            actual = expected + timedelta(days=1 if late else -1)
            po = PurchaseOrder(po_number=po_number, vendor_id=vendor.id, requested_by_id=current_user.id, description=product_name, quantity=20 + index, unit_price=price, total_amount=price * (20 + index), expected_delivery_date=expected, actual_delivery_date=actual, status=POStatus.DELIVERED)
            db.add(po)
            db.flush()
            db.add(PurchaseOrderItem(purchase_order_id=po.id, product_id=product.id, item_name=product_name, quantity=20 + index, unit_price=price, total_amount=price * (20 + index)))
            created["purchase_orders"] += 1
        delivery_number = f"DLV-DEMO-{1000 + index}"
        if not db.query(Delivery.id).filter(Delivery.delivery_number == delivery_number).first():
            db.add(Delivery(delivery_number=delivery_number, purchase_order_id=po.id, vendor_id=vendor.id, expected_delivery_date=po.expected_delivery_date, actual_delivery_date=po.actual_delivery_date, status=DeliveryStatus.DELIVERED, delay_days=late, received_goods=True, delivery_notes="Generated supporting delivery record"))
            created["deliveries"] += 1
        invoice_number = f"INV-DEMO-{1000 + index}"
        if not db.query(Invoice.id).filter(Invoice.invoice_number == invoice_number).first():
            db.add(Invoice(invoice_number=invoice_number, purchase_order_id=po.id, vendor_id=vendor.id, invoice_date=datetime.utcnow() - timedelta(days=index), due_date=datetime.utcnow() + timedelta(days=30), payment_date=datetime.utcnow() - timedelta(days=1) if index % 2 == 0 else None, invoice_amount=po.total_amount, payment_status=InvoiceStatus.PAID if index % 2 == 0 else InvoiceStatus.APPROVED))
            created["invoices"] += 1
        if not db.query(QualityInspection.id).filter(QualityInspection.purchase_order_id == po.id).first():
            db.add(QualityInspection(purchase_order_id=po.id, vendor_id=vendor.id, inspected_by_id=current_user.id, inspection_date=datetime.utcnow(), quality_score=quality, defective_quantity=late, remarks="Generated inspection for demonstration"))
            created["quality_inspections"] += 1
        contract_number = f"CT-DEMO-{1000 + index}"
        if not db.query(Contract.id).filter(Contract.contract_number == contract_number).first():
            db.add(Contract(vendor_id=vendor.id, title=f"{company} annual agreement", contract_number=contract_number, start_date=datetime.utcnow() - timedelta(days=120), end_date=datetime.utcnow() + timedelta(days=30 * (index + 1)), status=ContractStatus.ACTIVE, is_compliant=index != 4, renewal_notice_days=60, terms="Generated supporting contract terms."))
            created["contracts"] += 1
        contract = db.query(Contract).filter(Contract.contract_number == contract_number).first()

        # The reference Vendor dashboard includes certificates and documents.
        # Create small local text files in the Docker uploads volume so demo
        # downloads work too; never pretend these are external certifications.
        upload_dir = Path(os.getenv("UPLOAD_DIR", "/app/uploads"))
        for title, document_type, expiry_days in (
            ("Company registration certificate", DocumentType.CERTIFICATE, 360),
            ("Quality compliance certificate", DocumentType.COMPLIANCE, 180),
            ("Insurance certificate", DocumentType.INSURANCE, 90),
        ):
            storage_key = f"demo-{index}-{document_type.value}.txt"
            if db.query(VendorDocument.id).filter(VendorDocument.storage_key == storage_key).first():
                continue
            try:
                upload_dir.mkdir(parents=True, exist_ok=True)
                (upload_dir / storage_key).write_text(
                    f"VendorIQ generated local demo document: {title} for {company}.\n",
                    encoding="utf-8",
                )
            except OSError:
                # Do not create a database record that advertises a download
                # when the configured storage location is unavailable.
                continue
            db.add(VendorDocument(
                vendor_id=vendor.id, uploaded_by_id=current_user.id, contract_id=contract.id if contract else None,
                title=title, type=document_type, filename=f"{company.lower().replace(' ', '-')}-{document_type.value}.txt",
                storage_key=storage_key, expires_at=datetime.utcnow() + timedelta(days=expiry_days),
            ))
            created["documents"] += 1
        # The endpoint is safe to run repeatedly: keep one generated baseline
        # per supplier rather than adding duplicate performance observations at
        # every Docker restart.
        if not db.query(PerformanceRecord.id).filter(PerformanceRecord.vendor_id == vendor.id).first():
            db.add(PerformanceRecord(vendor_id=vendor.id, recorded_by_id=current_user.id, on_time_deliveries=on_time, delayed_deliveries=late, quality_rating=quality / 20, response_time_hours=8 + index, issue_resolution_hours=18 + index, order_completion_rate=96 - min(late, 5)))

    vendor_user = db.query(User).filter(User.role == RoleEnum.VENDOR, User.is_active.is_(True)).first()
    if vendor_user and vendor_ids and not db.query(Message.id).filter(Message.subject == "Welcome to the VendorIQ demo workspace").first():
        db.add(Message(
            sender_id=current_user.id, recipient_id=vendor_user.id, vendor_id=vendor_ids[0],
            subject="Welcome to the VendorIQ demo workspace",
            body="Your supplier portal contains your orders, delivery commitments, contracts and supporting documents.",
            type=MessageType.GENERAL,
        ))
        created["messages"] += 1
    log_activity(db, current_user.id, "seeded", "generated_supporting_data", None, "Created/verified DataCo-compatible demo data")
    db.commit()
    for vendor_id in vendor_ids:
        recompute_reliability_score(db, vendor_id)
    return {**created, "message": "Generated supporting business data loaded. It is safe to run this action again."}
