"""VendorIQ database seed/import entry point.

The project now uses the DataCo Smart Supply Chain Dataset as its primary
operational dataset. Supplemental VendorIQ-only entities are generated by
import_dataco.py because they are not present in DataCo.
"""

from import_dataco import main


if __name__ == "__main__":
    main()
