"""add contract upload metadata

Revision ID: 09237453ccc0
Revises: 1674eb77c68b
Create Date: 2026-08-06 17:11:51.988087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09237453ccc0'
down_revision: Union[str, None] = '1674eb77c68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('mime_type', sa.String(), nullable=True))
    op.alter_column('contracts', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('contracts', 'mime_type')
    op.drop_column('contracts', 'file_size')
    # ### end Alembic commands ###
