"""Create Milestone 2 vendor, procurement, purchasing, contract, and messaging tables."""
from alembic import op
import sqlalchemy as sa

revision = "20260804_0002"
down_revision = "20260802_0001"
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table("vendor_categories", sa.Column("id",sa.Integer,primary_key=True), sa.Column("name",sa.String(100),nullable=False,unique=True), sa.Column("description",sa.String(255)), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    op.create_index("ix_vendor_categories_name","vendor_categories",["name"])
    op.create_table("vendors", sa.Column("id",sa.Integer,primary_key=True), sa.Column("company_name",sa.String(255),nullable=False), sa.Column("registration_number",sa.String(100),nullable=False,unique=True), sa.Column("gst_number",sa.String(50),nullable=False,unique=True), sa.Column("email",sa.String(320),nullable=False), sa.Column("phone",sa.String(30),nullable=False), sa.Column("address",sa.Text,nullable=False), sa.Column("city",sa.String(100),nullable=False), sa.Column("state",sa.String(100),nullable=False), sa.Column("country",sa.String(100),nullable=False), sa.Column("postal_code",sa.String(20),nullable=False), sa.Column("website",sa.String(255)), sa.Column("category_id",sa.Integer,sa.ForeignKey("vendor_categories.id",ondelete="RESTRICT"),nullable=False), sa.Column("approval_status",sa.String(30),nullable=False,server_default="Pending"), sa.Column("created_by",sa.Integer,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    for name,column in (("ix_vendors_company_name","company_name"),("ix_vendors_registration_number","registration_number"),("ix_vendors_gst_number","gst_number"),("ix_vendors_category_id","category_id"),("ix_vendors_approval_status","approval_status"),("ix_vendors_created_by","created_by")): op.create_index(name,"vendors",[column])
    op.create_table("vendor_contacts",sa.Column("id",sa.Integer,primary_key=True),sa.Column("vendor_id",sa.Integer,sa.ForeignKey("vendors.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(150),nullable=False),sa.Column("designation",sa.String(100)),sa.Column("email",sa.String(320),nullable=False),sa.Column("phone",sa.String(30)),sa.Column("is_primary",sa.Boolean,nullable=False,server_default=sa.false()))
    op.create_index("ix_vendor_contacts_vendor_id","vendor_contacts",["vendor_id"])
    op.create_table("procurement_requests",sa.Column("id",sa.Integer,primary_key=True),sa.Column("title",sa.String(255),nullable=False),sa.Column("department",sa.String(150),nullable=False),sa.Column("description",sa.Text,nullable=False),sa.Column("estimated_cost",sa.Numeric(14,2),nullable=False),sa.Column("priority",sa.String(20),nullable=False,server_default="Medium"),sa.Column("required_date",sa.Date,nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="Pending"),sa.Column("line_items",sa.JSON,nullable=False),sa.Column("created_by",sa.Integer,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by",sa.Integer,sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    for name,column in (("ix_procurement_requests_title","title"),("ix_procurement_requests_status","status"),("ix_procurement_requests_created_by","created_by")): op.create_index(name,"procurement_requests",[column])
    op.create_table("purchase_orders",sa.Column("id",sa.Integer,primary_key=True),sa.Column("po_number",sa.String(50),nullable=False,unique=True),sa.Column("vendor_id",sa.Integer,sa.ForeignKey("vendors.id",ondelete="RESTRICT"),nullable=False),sa.Column("procurement_request_id",sa.Integer,sa.ForeignKey("procurement_requests.id",ondelete="RESTRICT"),nullable=False,unique=True),sa.Column("issue_date",sa.Date,nullable=False),sa.Column("expected_delivery_date",sa.Date,nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="Created"),sa.Column("total_amount",sa.Numeric(14,2),nullable=False),sa.Column("invoice_path",sa.String(500)),sa.Column("delivery_proof_path",sa.String(500)),sa.Column("created_by",sa.Integer,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    for name,column in (("ix_purchase_orders_po_number","po_number"),("ix_purchase_orders_vendor_id","vendor_id"),("ix_purchase_orders_status","status")): op.create_index(name,"purchase_orders",[column])
    op.create_table("po_items",sa.Column("id",sa.Integer,primary_key=True),sa.Column("purchase_order_id",sa.Integer,sa.ForeignKey("purchase_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("item_name",sa.String(255),nullable=False),sa.Column("quantity",sa.Numeric(12,2),nullable=False),sa.Column("unit_price",sa.Numeric(14,2),nullable=False),sa.Column("subtotal",sa.Numeric(14,2),nullable=False)); op.create_index("ix_po_items_purchase_order_id","po_items",["purchase_order_id"])
    op.create_table("contracts",sa.Column("id",sa.Integer,primary_key=True),sa.Column("contract_number",sa.String(80),nullable=False,unique=True),sa.Column("vendor_id",sa.Integer,sa.ForeignKey("vendors.id",ondelete="RESTRICT"),nullable=False),sa.Column("start_date",sa.Date,nullable=False),sa.Column("end_date",sa.Date,nullable=False),sa.Column("renewal_notice_days",sa.Integer,nullable=False,server_default="30"),sa.Column("compliance_status",sa.String(30),nullable=False,server_default="Pending"),sa.Column("terms",sa.Text,nullable=False),sa.Column("contract_file",sa.String(500)),sa.Column("created_by",sa.Integer,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    for name,column in (("ix_contracts_contract_number","contract_number"),("ix_contracts_vendor_id","vendor_id"),("ix_contracts_end_date","end_date")): op.create_index(name,"contracts",[column])
    op.create_table("contract_documents",sa.Column("id",sa.Integer,primary_key=True),sa.Column("contract_id",sa.Integer,sa.ForeignKey("contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("file_name",sa.String(255),nullable=False),sa.Column("file_path",sa.String(500),nullable=False),sa.Column("uploaded_by",sa.Integer,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False)); op.create_index("ix_contract_documents_contract_id","contract_documents",["contract_id"])
    op.create_table("messages",sa.Column("id",sa.Integer,primary_key=True),sa.Column("purchase_order_id",sa.Integer,sa.ForeignKey("purchase_orders.id",ondelete="CASCADE")),sa.Column("contract_id",sa.Integer,sa.ForeignKey("contracts.id",ondelete="CASCADE")),sa.Column("sender_id",sa.Integer,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("receiver_id",sa.Integer,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("subject",sa.String(255),nullable=False),sa.Column("message",sa.Text,nullable=False),sa.Column("attachment_path",sa.String(500)),sa.Column("is_read",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.CheckConstraint("(purchase_order_id IS NOT NULL AND contract_id IS NULL) OR (purchase_order_id IS NULL AND contract_id IS NOT NULL)",name="ck_messages_one_thread"))
    for name,column in (("ix_messages_purchase_order_id","purchase_order_id"),("ix_messages_contract_id","contract_id"),("ix_messages_sender_id","sender_id"),("ix_messages_receiver_id","receiver_id")): op.create_index(name,"messages",[column])
    op.create_table("audit_logs",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity",sa.String(100),nullable=False),sa.Column("entity_id",sa.Integer),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    for name,column in (("ix_audit_logs_user_id","user_id"),("ix_audit_logs_action","action"),("ix_audit_logs_entity","entity"),("ix_audit_logs_entity_id","entity_id")): op.create_index(name,"audit_logs",[column])

def downgrade() -> None:
    for table in ("audit_logs","messages","contract_documents","contracts","po_items","purchase_orders","procurement_requests","vendor_contacts","vendors","vendor_categories"): op.drop_table(table)
