"""milestone_three_additions

Revision ID: 5a07e0a78aa1
Revises: 20260804_0002
Create Date: 2026-08-18 18:25:30.715289

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a07e0a78aa1'
down_revision: Union[str, Sequence[str], None] = '20260804_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('related_entity', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_severity'), 'notifications', ['severity'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('vendor_reliability_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_category', sa.String(length=30), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('contract_compliance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_response_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('purchase_order_performance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('breakdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_reliability_history_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_reliability_history'))
    )
    op.create_index(op.f('ix_vendor_reliability_history_created_at'), 'vendor_reliability_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_vendor_reliability_history_vendor_id'), 'vendor_reliability_history', ['vendor_id'], unique=False)
    op.drop_constraint(op.f('uq_contracts_contract_number'), 'contracts', type_='unique')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.drop_constraint(op.f('uq_purchase_orders_po_number'), 'purchase_orders', type_='unique')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('uq_vendor_categories_name'), 'vendor_categories', type_='unique')
    op.drop_index(op.f('ix_vendor_categories_name'), table_name='vendor_categories')
    op.create_index(op.f('ix_vendor_categories_name'), 'vendor_categories', ['name'], unique=True)
    op.add_column('vendors', sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vendors', sa.Column('risk_category', sa.String(length=30), nullable=True))
    op.add_column('vendors', sa.Column('score_breakdown', sa.JSON(), nullable=True))
    op.add_column('vendors', sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_vendors_gst_number'), 'vendors', type_='unique')
    op.drop_constraint(op.f('uq_vendors_registration_number'), 'vendors', type_='unique')
    op.drop_index(op.f('ix_vendors_gst_number'), table_name='vendors')
    op.create_index(op.f('ix_vendors_gst_number'), 'vendors', ['gst_number'], unique=True)
    op.drop_index(op.f('ix_vendors_registration_number'), table_name='vendors')
    op.create_index(op.f('ix_vendors_registration_number'), 'vendors', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_registration_number'), table_name='vendors')
    op.create_index(op.f('ix_vendors_registration_number'), 'vendors', ['registration_number'], unique=False)
    op.drop_index(op.f('ix_vendors_gst_number'), table_name='vendors')
    op.create_index(op.f('ix_vendors_gst_number'), 'vendors', ['gst_number'], unique=False)
    op.create_unique_constraint(op.f('uq_vendors_registration_number'), 'vendors', ['registration_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_vendors_gst_number'), 'vendors', ['gst_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('vendors', 'last_calculated_at')
    op.drop_column('vendors', 'score_breakdown')
    op.drop_column('vendors', 'risk_category')
    op.drop_column('vendors', 'reliability_score')
    op.drop_index(op.f('ix_vendor_categories_name'), table_name='vendor_categories')
    op.create_index(op.f('ix_vendor_categories_name'), 'vendor_categories', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_vendor_categories_name'), 'vendor_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_unique_constraint(op.f('uq_purchase_orders_po_number'), 'purchase_orders', ['po_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=False)
    op.create_unique_constraint(op.f('uq_contracts_contract_number'), 'contracts', ['contract_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_vendor_reliability_history_vendor_id'), table_name='vendor_reliability_history')
    op.drop_index(op.f('ix_vendor_reliability_history_created_at'), table_name='vendor_reliability_history')
    op.drop_table('vendor_reliability_history')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_severity'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
