"""add_risk_intelligence

Revision ID: 7550bb791a96
Revises: 5a07e0a78aa1
Create Date: 2026-08-25 20:22:51.490851

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7550bb791a96'
down_revision: Union[str, Sequence[str], None] = '5a07e0a78aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('overall_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vendors', sa.Column('risk_level', sa.String(length=30), nullable=True))
    op.add_column('vendors', sa.Column('risk_explanation', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('risk_trend', sa.String(length=30), nullable=True))
    op.add_column('vendors', sa.Column('early_warning', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('operational_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vendors', sa.Column('compliance_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vendors', sa.Column('financial_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vendors', sa.Column('cyber_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vendors', sa.Column('dependency_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vendors', sa.Column('financial_health_indicator', sa.String(length=50), server_default='Healthy', nullable=True))
    op.add_column('vendors', sa.Column('outstanding_exposure', sa.Numeric(precision=14, scale=2), server_default='0.0', nullable=True))
    op.add_column('vendors', sa.Column('payment_issues_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('vendors', sa.Column('security_assessment_status', sa.String(length=50), server_default='Passed', nullable=True))
    op.add_column('vendors', sa.Column('security_certification_status', sa.String(length=50), server_default='Certified', nullable=True))
    op.add_column('vendors', sa.Column('security_incidents_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('vendors', sa.Column('alternative_vendors_count', sa.Integer(), server_default='1', nullable=True))
    op.add_column('vendors', sa.Column('is_critical_supplier', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('vendors', sa.Column('blast_radius_level', sa.String(length=30), server_default='Low', nullable=True))
    op.add_column('vendors', sa.Column('blast_radius_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'blast_radius_explanation')
    op.drop_column('vendors', 'blast_radius_level')
    op.drop_column('vendors', 'is_critical_supplier')
    op.drop_column('vendors', 'alternative_vendors_count')
    op.drop_column('vendors', 'security_incidents_count')
    op.drop_column('vendors', 'security_certification_status')
    op.drop_column('vendors', 'security_assessment_status')
    op.drop_column('vendors', 'payment_issues_count')
    op.drop_column('vendors', 'outstanding_exposure')
    op.drop_column('vendors', 'financial_health_indicator')
    op.drop_column('vendors', 'dependency_risk_score')
    op.drop_column('vendors', 'cyber_risk_score')
    op.drop_column('vendors', 'financial_risk_score')
    op.drop_column('vendors', 'compliance_risk_score')
    op.drop_column('vendors', 'operational_risk_score')
    op.drop_column('vendors', 'early_warning')
    op.drop_column('vendors', 'risk_trend')
    op.drop_column('vendors', 'risk_explanation')
    op.drop_column('vendors', 'risk_level')
    op.drop_column('vendors', 'overall_risk_score')
    # ### end Alembic commands ###
