"""Add PRItem model

Revision ID: 774f6f383dac
Revises: e7f77dcd7073
Create Date: 2026-08-06 01:59:03.392043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774f6f383dac'
down_revision: Union[str, None] = 'e7f77dcd7073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['procurement_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_items_id'), 'pr_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pr_items_id'), table_name='pr_items')
    op.drop_table('pr_items')
    # ### end Alembic commands ###
