"""create contracts table

Revision ID: 9b3280705077
Revises: 4e9c6b8b3c25
Create Date: 2026-08-13 00:00:59.385444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3280705077'
down_revision: Union[str, Sequence[str], None] = '4e9c6b8b3c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_requests_id'), table_name='procurement_requests')
    op.drop_table('procurement_requests')
    op.alter_column('deliveries', 'delivery_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.drop_constraint(op.f('deliveries_vendor_id_fkey'), 'deliveries', type_='foreignkey')
    op.drop_constraint(op.f('deliveries_purchase_order_id_fkey'), 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deliveries', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('purchase_orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendors', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.alter_column('purchase_orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('deliveries_purchase_order_id_fkey'), 'deliveries', 'purchase_orders', ['purchase_order_id'], ['id'])
    op.create_foreign_key(op.f('deliveries_vendor_id_fkey'), 'deliveries', 'vendors', ['vendor_id'], ['id'])
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.alter_column('deliveries', 'delivery_notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('procurement_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('request_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_requests_pkey')),
    sa.UniqueConstraint('request_number', name=op.f('procurement_requests_request_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_procurement_requests_id'), 'procurement_requests', ['id'], unique=False)
    # ### end Alembic commands ###
