"""Add DataCo models

Revision ID: b0f92c10ca31
Revises: e8895d2fd513
Create Date: 2026-08-08 16:11:57.283250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f92c10ca31'
down_revision: Union[str, None] = 'e8895d2fd513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_product_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_external_product_id'), 'products', ['external_product_id'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('shipping_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_shipping_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('shipping_mode', sa.String(), nullable=True),
    sa.Column('days_real', sa.Float(), nullable=True),
    sa.Column('days_scheduled', sa.Float(), nullable=True),
    sa.Column('late_risk_flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('quality_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('defect_count', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_inspections_id'), 'quality_inspections', ['id'], unique=False)
    op.add_column('po_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('po_items', sa.Column('external_item_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_po_items_external_item_id'), 'po_items', ['external_item_id'], unique=True)
    op.create_foreign_key(None, 'po_items', 'products', ['product_id'], ['id'])
    op.add_column('purchase_orders', sa.Column('source', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('external_order_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_external_order_id'), 'purchase_orders', ['external_order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_orders_external_order_id'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'external_order_id')
    op.drop_column('purchase_orders', 'source')
    op.drop_constraint(None, 'po_items', type_='foreignkey')
    op.drop_index(op.f('ix_po_items_external_item_id'), table_name='po_items')
    op.drop_column('po_items', 'external_item_id')
    op.drop_column('po_items', 'product_id')
    op.drop_index(op.f('ix_quality_inspections_id'), table_name='quality_inspections')
    op.drop_table('quality_inspections')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_external_product_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
