"""initial migration

Revision ID: e91a4ba434a2
Revises: 
Create Date: 2026-08-09 18:52:04.891381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91a4ba434a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.alter_column('vendors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vendors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vendors', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.create_unique_constraint(None, 'vendors', ['email'])
    op.create_foreign_key(None, 'vendors', 'vendor_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_constraint(None, 'vendors', type_='unique')
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    op.alter_column('vendors', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vendors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vendors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('purchase_orders', 'total_cost',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
