const ROLE_ACCESS = {

    "Administrator": {
        dashboard: true,
        userManagement: true,
        vendors: true,
        products: true,
        procurementRequests: true,
        purchaseOrders: true,
        deliveries: true,
        contracts: true,
        invoices: true,
        qualityInspections: true,
        communication: true,
        notifications: true,
        analytics: true,
        reports: true,
        settings: true,
        auditLogs: true,
        help: true
    },

    "Procurement Manager": {
        dashboard: true,
        userManagement: false,
        vendors: true,
        products: true,
        procurementRequests: true,
        purchaseOrders: true,
        deliveries: true,
        contracts: true,
        invoices: true,
        qualityInspections: true,
        communication: true,
        notifications: true,
        analytics: true,
        reports: true,
        settings: false,
        auditLogs: false,
        help: true
    },

    "Supply Chain Manager": {
        dashboard: true,
        userManagement: false,
        vendors: true,
        products: true,
        procurementRequests: true,
        purchaseOrders: true,
        deliveries: true,
        contracts: true,
        invoices: false,
        qualityInspections: true,
        communication: true,
        notifications: true,
        analytics: true,
        reports: true,
        settings: false,
        auditLogs: false,
        help: true
    },

    "Vendor": {
        dashboard: true,
        userManagement: false,
        vendors: false,
        products: true,
        procurementRequests: false,
        purchaseOrders: true,
        deliveries: true,
        contracts: true,
        invoices: true,
        qualityInspections: false,
        communication: true,
        notifications: true,
        analytics: false,
        reports: false,
        settings: false,
        auditLogs: false,
        help: true
    },

    "Finance Officer": {
        dashboard: true,
        userManagement: false,
        vendors: true,
        products: false,
        procurementRequests: false,
        purchaseOrders: true,
        deliveries: false,
        contracts: true,
        invoices: true,
        qualityInspections: false,
        communication: false,
        notifications: true,
        analytics: true,
        reports: true,
        settings: false,
        auditLogs: false,
        help: true
    },

    "Auditor": {
        dashboard: true,
        userManagement: false,
        vendors: true,
        products: false,
        procurementRequests: true,
        purchaseOrders: true,
        deliveries: true,
        contracts: true,
        invoices: true,
        qualityInspections: true,
        communication: false,
        notifications: true,
        analytics: false,
        reports: true,
        settings: false,
        auditLogs: true,
        help: true
    }
};